# Generated by Django 2.0.7 on 2018-08-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='created_at',
        ),
        migrations.AddField(
            model_name='grocery',
            name='recipe',
            field=models.CharField(default='Miscellaneous', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grocery',
            name='unit',
            field=models.CharField(choices=[('x', 'Units'), ('tsp', 'Teaspoons'), ('tbsp', 'Tablespoons'), ('cup', 'Cups'), ('oz', 'Ounces'), ('lb', 'Pounds'), ('kg', 'Kilograms')], default='x', max_length=4),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
