# Generated by Django 2.0.7 on 2018-08-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('grocery_list', '0002_auto_20180808_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='unit',
        ),
        migrations.AddField(
            model_name='grocery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2018-08-08 00:00:00'),
            preserve_default=False,
        ),
    ]
