# Generated by Django 2.0.7 on 2018-08-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('grocery_list', '0004_remove_grocery_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grocery',
            name='recipe',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grocery',
            name='unit',
            field=models.CharField(choices=[('x', 'Units'), ('tsp', 'Teaspoons'), ('tbsp', 'Tablespoons'), ('cup', 'Cups'), ('oz', 'Ounces'), ('lb', 'Pounds'), ('kg', 'Kilograms')], default='x', max_length=4),
        ),
    ]
