# Generated by Django 2.0.7 on 2018-08-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('grocery_list', '0005_auto_20180813_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='grocery_list.Grocery'),
        ),
    ]
