# Generated by Django 2.0.7 on 2018-08-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('grocery_list', '0006_auto_20180813_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='groceries',
        ),
        migrations.AddField(
            model_name='grocery',
            name='containing_recipe',
            field=models.CharField(default='misc', max_length=200),
            preserve_default=False,
        ),
    ]
