# Generated by Django 2.0.7 on 2018-08-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('grocery_list', '0008_auto_20180816_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('groceries', models.ManyToManyField(to='grocery_list.Grocery')),
            ],
        ),
        migrations.RemoveField(
            model_name='grocerylist',
            name='name',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2018-02-14 00:00:00'),
            preserve_default=False,
        ),
    ]
