# Generated by Django 2.0.7 on 2018-08-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0009_auto_20180816_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='containing_recipe',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
